name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
        repository: laurentkempe/dockerwebapi/dockerwebapi
        auto_tag: true
