name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-16.04
 
    steps:
    - uses: actions/checkout@v1
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/laurentkempe/dockerwebapi/dockerwebapi
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
        dockerfile: Dockerfile
